framework:
  workflows:
    blog_publishing:
      type: 'workflow' # or 'state_machine'
      audit_trail:
        enabled: true
      marking_store:
        type: 'single_state' # or 'multiple_state'
        arguments:
          - 'currentPlace'
      supports:
        - App\Entity\Post
      initial_place: draft
      places:
        - draft
        - review
        - rejected
        - published
      transitions:
        to_review:
          from: draft
          to:   review
        publish:
          from: review
          to:   published
        reject:
          from: review
          to:   rejected
        我修改了之后就可以重新 review 了:
          from: rejected
          to: review
